name: wsa_pacman
description: A GUI package manager and package installer for Windows Subsystem for Android (WSA).
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_gen: any
    
  # UIとシステム関連のメジャーアップデート
  fluent_ui: ^4.0.0
  win32: ^3.1.4
  provider: ^6.1.1
  shared_value: ^2.1.2
  synchronized: ^3.1.0
  system_theme: ^2.1.1
  flutter_acrylic: ^1.1.1
  url_strategy: ^0.2.0
  yaml: ^3.1.2
  protobuf: ^2.1.0
  mdi: ^5.0.0-nullsafety.0
  base32: ^2.1.1
  charset: ^0.1.1

  # 公式パッケージでの動作検証
  archive: ^3.4.0
  jovial_svg: ^1.1.16

  # カスタム修正が含まれている可能性が高いものはGitフォークを維持
  bitsdojo_window:
    git:
      url: https://github.com/alesimula/bitsdojo_window.git
      path: bitsdojo_window
      ref: master
  smooth_scroll_multiplatform:
    git: https://github.com/alesimula/dyn_mouse_scroll.git
  ffi: ^2.2.0
  path: ^1.9.1
  collection: ^1.19.1
  crypto: ^3.0.7
  intl: ^0.20.2

  fixnum: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/missing_icon_background.si
    - assets/icons/missing_icon_foreground.si
    - assets/icons/missing_icon_legacy.si
    - assets/images/logo.png
